packageExtensions:
  '@ledgerhq/device-transport-kit-web-ble@*':
    peerDependencies:
      '@ledgerhq/device-management-kit': '>=0.11.0 <0.12.0'
  '@ledgerhq/device-transport-kit-web-hid@*':
    peerDependencies:
      '@ledgerhq/device-management-kit': '>=0.11.0 <0.12.0'
compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

enableTelemetry: false

nodeLinker: node-modules
